"""
src/agent.py
LangGraph agent definition.

Graph structure:
  START → llm_node → (tool_node if tool call, else END)
           ↑              |
           └──────────────┘

The agent uses an LLM (configurable via LLM_PROVIDER env var) bound to the
three tools. It autonomously decides which tool to call based on the user message.
Conversation memory is maintained in-process per session_id.
"""

import os
from typing import Annotated, TypedDict

from langchain_core.messages import AIMessage, BaseMessage, HumanMessage, SystemMessage
from langchain_openai import ChatOpenAI
from langchain_anthropic import ChatAnthropic
from langgraph.graph import END, START, StateGraph
from langgraph.graph.message import add_messages
from langgraph.prebuilt import ToolNode

from src.tools import ALL_TOOLS

# ── System prompt ─────────────────────────────────────────────────────────────
SYSTEM_PROMPT = """You are a Spotify AI music detection assistant. You are an expert
on Spotify audio features and the differences between human-made and AI-generated music.

Your domain: classifying whether a Spotify track was created by a human artist or
generated by an AI system, based on audio features such as acousticness, energy,
instrumentalness, tempo, danceability, and others.

You have access to three tools:

1. retrieval_tool – Use this when the user asks a factual or conceptual question
   about music, Spotify audio features, AI-generated music, how AI music differs
   from human music, music recommendation systems, or related topics.
   This searches a curated knowledge base of domain documents.

2. prediction_tool – Use this when the user provides specific numeric audio feature
   values and wants to know whether a track is Human-made or AI-Generated.
   You must collect all required features before calling this tool. The required
   fields are: acousticness, danceability, duration_ms, energy, instrumentalness,
   key, liveness, loudness, mode, speechiness, tempo, time_signature, valence,
   popularity, short_form.
   If the user provides partial features, ask for the missing ones before calling.

3. dataset_stats_tool – Use this when the user asks about statistics, averages,
   distributions, or counts of any column in the Spotify 2026 dataset (e.g.
   "what is the average energy of tracks?", "how many AI tracks are in the dataset?").

Guidelines:
- Never ask the user to specify which tool to use — infer it from their message.
- When you give a prediction result, connect it to domain knowledge where relevant
  (e.g. explain why high energy + low acousticness signals AI generation).
- Be concise, informative, and conversational.
- For follow-up questions referencing previous messages, use conversation history
  to infer context (e.g. "what if acousticness was 0.9?" — recall the previous
  feature set and update only that field).
- Class labels: 0 = Human-made, 1 = AI-Generated.
"""

# ── Agent state ───────────────────────────────────────────────────────────────
class AgentState(TypedDict):
    messages: Annotated[list[BaseMessage], add_messages]


# ── In-memory session store ───────────────────────────────────────────────────
# Maps session_id -> list of BaseMessage
_session_histories: dict[str, list[BaseMessage]] = {}


def get_session_history(session_id: str) -> list[BaseMessage]:
    """Return the conversation history for a session, creating it if new."""
    if session_id not in _session_histories:
        _session_histories[session_id] = []
    return _session_histories[session_id]


def append_to_session(session_id: str, messages: list[BaseMessage]) -> None:
    """Append new messages to a session's history."""
    history = get_session_history(session_id)
    history.extend(messages)


def clear_session(session_id: str) -> None:
    """Clear conversation history for a session."""
    _session_histories.pop(session_id, None)


# ── LLM factory ───────────────────────────────────────────────────────────────
def _build_llm():
    """
    Build the LLM based on the LLM_PROVIDER environment variable.
    Supported values: 'openai' (default), 'anthropic'
    """
    provider = os.getenv("LLM_PROVIDER", "openai").lower()

    if provider == "anthropic":
        api_key = os.getenv("ANTHROPIC_API_KEY")
        if not api_key:
            raise EnvironmentError("ANTHROPIC_API_KEY environment variable not set.")
        llm = ChatAnthropic(
            model="claude-3-haiku-20240307",
            api_key=api_key,
            temperature=0,
        )
    else:  # default: openai
        api_key = os.getenv("OPENAI_API_KEY")
        if not api_key:
            raise EnvironmentError("OPENAI_API_KEY environment variable not set.")
        llm = ChatOpenAI(
            model="gpt-4o-mini",
            api_key=api_key,
            temperature=0,
        )

    return llm.bind_tools(ALL_TOOLS)


# ── Graph builder ─────────────────────────────────────────────────────────────
def build_graph():
    """Compile and return the LangGraph agent graph."""
    llm_with_tools = _build_llm()

    def llm_node(state: AgentState) -> AgentState:
        messages = state["messages"]
        # Prepend system prompt if not already present
        if not messages or not isinstance(messages[0], SystemMessage):
            messages = [SystemMessage(content=SYSTEM_PROMPT)] + messages
        response = llm_with_tools.invoke(messages)
        return {"messages": [response]}

    def should_continue(state: AgentState) -> str:
        """Route to tool_node if the LLM made a tool call, else END."""
        last_message = state["messages"][-1]
        if hasattr(last_message, "tool_calls") and last_message.tool_calls:
            return "tool_node"
        return END

    tool_node = ToolNode(ALL_TOOLS)

    graph = StateGraph(AgentState)
    graph.add_node("llm_node", llm_node)
    graph.add_node("tool_node", tool_node)

    graph.add_edge(START, "llm_node")
    graph.add_conditional_edges("llm_node", should_continue)
    graph.add_edge("tool_node", "llm_node")

    return graph.compile()


# ── Singleton compiled graph ──────────────────────────────────────────────────
_graph = None

def get_graph():
    global _graph
    if _graph is None:
        _graph = build_graph()
    return _graph


# ── Public interface ──────────────────────────────────────────────────────────
def chat(message: str, session_id: str) -> str:
    """
    Send a user message and return the agent's response.

    Args:
        message:    The user's natural-language input.
        session_id: Unique identifier for the conversation session.

    Returns:
        The agent's response as a plain string.
    """
    graph = get_graph()

    # Build message list: history + new user message
    history = get_session_history(session_id)
    new_message = HumanMessage(content=message)
    all_messages = history + [new_message]

    # Run the graph
    result = graph.invoke({"messages": all_messages})

    # Extract the final AI message
    response_messages = result["messages"]
    ai_response = ""
    for msg in reversed(response_messages):
        if isinstance(msg, AIMessage) and msg.content:
            ai_response = msg.content
            break

    # Persist the full updated history (including tool messages)
    _session_histories[session_id] = [SystemMessage(content=SYSTEM_PROMPT)] + response_messages

    return ai_response


# ── Standalone test ───────────────────────────────────────────────────────────
if __name__ == "__main__":
    from dotenv import load_dotenv
    load_dotenv()

    sid = "test_session"
    print("Agent ready. Type 'quit' to exit.\n")

    while True:
        user_input = input("You: ").strip()
        if user_input.lower() in ("quit", "exit"):
            break
        response = chat(user_input, sid)
        print(f"Agent: {response}\n")
